### ISSUE TITLE
GPG signing support

### ISSUE THREAD

**Issue by ScarlettGatelyMoore** [appimage-packages/appimage-template#2]
Not high on priority until we have more functioning appimages ( we are not putting them out in the wild yet )

**Comment by probonopd** [comment]
Seems to be happening: https://github.com/appimage-packages/blinken/commit/959cd3cebbe7cb74261048f32d6aade9aa8bd50e :+1:

**Comment by ScarlettGatelyMoore** [comment]
This is implemented, however I do not see where an *.asc or *.sig file is at and therefore cannot provide one to upload for users to --verify with.

**Comment by ScarlettGatelyMoore** [comment]
embedded into appimage to be used by appimagekit validate.
