### ISSUE TITLE
Create frameworks bundle

### ISSUE THREAD

**Issue by ScarlettGatelyMoore** [appimage-packages/appimage-template#5]
Cut build time significantly for KDE appimages by creating a bundle archive of all the frameworks to share.

**Comment by star-buck** [comment]
But then apps are no longer selfcontained?
They depend on frameworks and sooner or later could malfunction if the
framework appimage deprecatesif the app goes up or the app stays and the
framework one renews.

**Comment by ScarlettGatelyMoore** [comment]
I only mean at build time. Not runtime.

**Comment by ScarlettGatelyMoore** [comment]
and yeah it would have to be constantly building on commits certainly. It is only in the thinking stage. And may never come to life.

**Comment by ScarlettGatelyMoore** [comment]
Went another directions and baked in qt related / toolchain resulting in acceptable buildtimes.
